import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const handleStart = (e) => {
    e.preventDefault();
    router.push("/main/home");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>FAZZPAY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to FAZZPAY</h1>
        <button className={styles.get} onClick={handleStart}>
          Get Started
        </button>
      </main>
    </div>
  );
}
